server:
  port: 8081

spring:
  application:
    name: product-service
  
endpoints:
  routes:
    sensitive: false


  
eureka:
    client:
        service-url:
            defaultZone: http://service-registry:8761/eureka
        fetch-registry: true
        register-with-eureka: true
