spring:
  application:
    name: service-registry
  zipkin:
    base-url: http://service-registry:8761/eureka/
    
  

server:
  port: 8761


eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
