server:
  port: 8082

spring:
  application:
    name: offer-service
    
spring:
  rabbitmq:
    username: guest
    password: guest
    host: http://rabbitmq:15672/
     
  
eureka:
    client:
        service-url:
            defaultZone: http://service-registry:8761/eureka
        fetch-registry: true
        register-with-eureka: true
