server:
  port: 8000

spring:
  application:
    name: api-gateway

zuul:
  ignoredServices: '*'
  routes:
    product-service:
      path: /product-service/**
      service-id: product-service
      stripPrefix: true
    offer-service:
      path: /offer-service/**
      serviceId: offer-service
      stripPrefix: true

endpoints:
  routes:
    sensitive: false

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
