server:
  port: 8000

spring:
  application:
    name: offer-service
  
eureka:
 instance:
   preferIpAddress: true
   hostname: eureka-0
 client:
   registerWithEureka: true
   fetchRegistry: true
   service-url:
     default-zone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
