server:
  port: 8081

spring:
  application:
    name: product-service
  
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
     



  
eureka:
    client:
        service-url:
            defaultZone: http://service-registry:8761/eureka
        fetch-registry: true
        register-with-eureka: true
  

