server:
  port: 8082

spring:
  application:
    name: offer-service
    
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://microservice:3000/"
            allowedMethods:
            - GET
            - POST
    
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
     
  
eureka:
    client:
        service-url:
            defaultZone: http://service-registry:8761/eureka
        fetch-registry: true
        register-with-eureka: true
