server:
  port: 8761

eureka:
  numberRegistrySyncRetries: 1
  instance:
    preferIpAddress: false
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/
  server:
    enable-self-preservation: true

---

spring:
  profiles: docker

eureka:
  numberRegistrySyncRetries: 1
  instance:
    preferIpAddress: true
    hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/
  server:
    enable-self-preservation: false
