server:
  port: 8000

spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      routes:
      - id: microservice
        uri: http://microservice:30000

zuul:
  ignoredServices: '*'
  routes:
    product-service:
      path: /product-service/**
      service-id: product-service
      stripPrefix: true
    offer-service:
      path: /offer-service/**
      serviceId: offer-service
      stripPrefix: true

endpoints:
  routes:
    sensitive: false


  
eureka:
    client:
        service-url:
            defaultZone: http://service-registry:8761/eureka
        fetch-registry: true
        register-with-eureka: true
