server:
  port: 8082

spring:
  application:
    name: offer-service
  
eureka:
    client:
        service-url:
            defaultZone: http://service-registry:8761/eureka
        fetch-registry: true
        register-with-eureka: true
