server:
  port: 8082

spring:
  application:
    name: offer-service
  
eureka:
 instance:
   preferIpAddress: true
 client:
   registerWithEureka: true
   fetchRegistry: true
   service-url:
     default-zone: http://service-registry:8761/eureka
