server:
  port: 8000

spring:
  application:
    name: api-gateway

zuul:
  ignoredServices: '*'
  routes:
    product-service:
      path: /product-service/**
      service-id: product-service
      stripPrefix: true
    offer-service:
      path: /offer-service/**
      serviceId: offer-service
      stripPrefix: true

endpoints:
  routes:
    sensitive: false


spring:
  application:
    name: api-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:admin@127.0.0.1:8761/eureka/
  instance:
    preferIpAddress: true

---

spring:
  profiles: docker
  application:
    name: api-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:admin@discovery:8761/eureka/
  instance:
    preferIpAddress: true
